/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteRouteImport } from "./routes/settings/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings/index";
import { Route as SettingsShortcutsRouteImport } from "./routes/settings/shortcuts";
import { Route as SettingsLanguageRouteImport } from "./routes/settings/language";
import { Route as SettingsAppearanceRouteImport } from "./routes/settings/appearance";
import { Route as SettingsAboutRouteImport } from "./routes/settings/about";

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: "/shortcuts",
  path: "/shortcuts",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: "/language",
  path: "/language",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => SettingsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/language": typeof SettingsLanguageRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/language": typeof SettingsLanguageRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings": typeof SettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/language": typeof SettingsLanguageRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/language"
    | "/settings/shortcuts"
    | "/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/language"
    | "/settings/shortcuts"
    | "/settings";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/language"
    | "/settings/shortcuts"
    | "/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren;
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/shortcuts": {
      id: "/settings/shortcuts";
      path: "/shortcuts";
      fullPath: "/settings/shortcuts";
      preLoaderRoute: typeof SettingsShortcutsRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/language": {
      id: "/settings/language";
      path: "/language";
      fullPath: "/settings/language";
      preLoaderRoute: typeof SettingsLanguageRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/appearance": {
      id: "/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/about": {
      id: "/settings/about";
      path: "/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof SettingsAboutRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute;
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsLanguageRoute: typeof SettingsLanguageRoute;
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
