/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteRouteImport } from "./routes/settings/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings/index";
import { Route as SettingsTranslateRouteImport } from "./routes/settings/translate";
import { Route as SettingsShortcutsRouteImport } from "./routes/settings/shortcuts";
import { Route as SettingsServiceRouteImport } from "./routes/settings/service";
import { Route as SettingsAboutRouteImport } from "./routes/settings/about";

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsTranslateRoute = SettingsTranslateRouteImport.update({
  id: "/translate",
  path: "/translate",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: "/shortcuts",
  path: "/shortcuts",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsServiceRoute = SettingsServiceRouteImport.update({
  id: "/service",
  path: "/service",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => SettingsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings/translate": typeof SettingsTranslateRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings/translate": typeof SettingsTranslateRoute;
  "/settings": typeof SettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/service": typeof SettingsServiceRoute;
  "/settings/shortcuts": typeof SettingsShortcutsRoute;
  "/settings/translate": typeof SettingsTranslateRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/settings/about"
    | "/settings/service"
    | "/settings/shortcuts"
    | "/settings/translate"
    | "/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings/about"
    | "/settings/service"
    | "/settings/shortcuts"
    | "/settings/translate"
    | "/settings";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/settings/about"
    | "/settings/service"
    | "/settings/shortcuts"
    | "/settings/translate"
    | "/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren;
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/translate": {
      id: "/settings/translate";
      path: "/translate";
      fullPath: "/settings/translate";
      preLoaderRoute: typeof SettingsTranslateRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/shortcuts": {
      id: "/settings/shortcuts";
      path: "/shortcuts";
      fullPath: "/settings/shortcuts";
      preLoaderRoute: typeof SettingsShortcutsRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/service": {
      id: "/settings/service";
      path: "/service";
      fullPath: "/settings/service";
      preLoaderRoute: typeof SettingsServiceRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/about": {
      id: "/settings/about";
      path: "/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof SettingsAboutRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute;
  SettingsServiceRoute: typeof SettingsServiceRoute;
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute;
  SettingsTranslateRoute: typeof SettingsTranslateRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsServiceRoute: SettingsServiceRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsTranslateRoute: SettingsTranslateRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
